[package]
name = "pod-replica"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
pod-common = { path = "../pod-common" }
tokio = { version = "1.0", features = ["full"] }
sled = "0.34"
tracing = "0.1"
prometheus = "0.14.0"
lazy_static = "1.4"